import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Background from './components/Background'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PRISMA EXERCISES',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Background/>
      <Navbar/>
      
        {children}</body>
    </html>
  )
}
